import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ShoppingCart } from 'lucide-react';
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Link from "next/link"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
        
        <nav className="flex flex-row justify-between">
          <h1>Food Delivery</h1>
          <div className="flex items-center gap-6">
            <Link href="login/">
              <Button variant="secondary" className="hover:bg-slate-300 text-lg">Sign in</Button>
            </Link>
            <ModeToggle />
            <button className="relative">
              <ShoppingCart className="h-6 w-6 transition-colors group-hover:text-primary mr-6 hover:bg-slate-200" />
              <Badge variant="destructive" className="absolute bottom-5 rounded-3xl right-1">2</Badge>
            </button>
          </div>
        </nav>
        {children}
        
        </ThemeProvider>
      </body>
    </html>
  );
}
